language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
- wget http://download.qt.io/official_releases/qt/5.6/5.6.2/qt-opensource-linux-x64-5.6.2.run
- sudo chmod +x qt-opensource-linux-x64-5.6.2.run

install:
- sudo ./qt-opensource-linux-x64-5.6.2.run
- git clone git://github.com/DamirPorobic/kColorPicker
- cd kColorPicker
- mkdir build && cd build
- cmake ..
- make && sudo make install
- cd ../..
- sudo ldconfig

jobs:
  include:
  - stage: build
    script:
    - mkdir build
    - cd build
    - cmake ..
    - make VERBOSE=1
  - stage: test
    script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TESTS=ON
    - make
    - xvfb-run make test CTEST_OUTPUT_ON_FAILURE=1