language: cpp
compiler: gcc
sudo: required
dist: xenial

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt594-xenial -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install mesa-common-dev libglu1-mesa-dev qt59base qt59tools qt59svg herbstluftwm
  - source /opt/qt*/bin/qt*-env.sh
  - git clone git://github.com/ksnip/kColorPicker
  - cd kColorPicker
  - mkdir build && cd build
  - cmake ..
  - make && sudo make install
  - cd ../..
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
  - sleep 3

before_script:
  - "herbstluftwm &"
  - sleep 1

jobs:
  include:
    - stage: build
      script:
        - mkdir build ; cd build
        - cmake .. ; make VERBOSE=1
    - stage: test
      script:
        - mkdir build ; cd build
        - cmake .. -DBUILD_TESTS=ON ; make
        - xvfb-run make test CTEST_OUTPUT_ON_FAILURE=1