name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'linux'
        install-deps: 'true'

    - name: Install dependencies
      run: sudo apt-get install extra-cmake-modules xvfb

    - name: Setup kColorPicker
      run: |
        git clone --depth 1 git://github.com/ksnip/kColorPicker
        cd kColorPicker
        mkdir build && cd build
        cmake ..
        make && sudo make install

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTS=ON && make VERBOSE=1
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: xvfb-run --auto-servernum --server-num=1 --server-args="-screen 0 1024x768x24" make test CTEST_OUTPUT_ON_FAILURE=1
      
